# Tox (http://tox.testrun.org/) es una herramienta para ejecutar
# pruebas en múltiples virtualenvs. Este archivo de configuración
# ejecutará el conjunto de pruebas en todas las versiones
# compatibles de Python. Para usarlo, "pip install tox" y luego
# ejecuta "tox" desde este directorio.

[tox]
envlist = py26, py27, py33

[testenv]
commands =
    pip install -r requisitos-desarrollo.txt
    spec
